### ISSUE TITLE
I can't send messages.

### ISSUE THREAD

**Issue by Titogelo** [WELTEN/dojo-ibl#139]
There a problem with the quota of the channels API. Whenever we reach the maximum which is 100 the messaging does not work anymore.

**Comment by Titogelo** [comment]
angular.js:12722 SyntaxError: Unexpected token T in JSON at position 0
    at Object.parse (native)
    at fromJson (http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:1272:20)
    at defaultHttpResponseTransform (http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:9658:28)
    at http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:9749:20
    at forEach (http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:341:34)
    at transformData (http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:9748:9)
    at transformResponse (http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:10521:37)
    at processQueue (http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:14991:42)
    at http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:15007:35
    at Scope.$eval (http://dojo-ibl.appspot.com/dist/js/vendor/angular.js:16251:44)

**Comment by Titogelo** [comment]
The T is because the server gives back this error that starts with T. "The API call xmpp.CreateChannel() required more quota than is available."

**Comment by Titogelo** [comment]
everytime that we reload we create a new channel. I need to optimise the way I create the channels.

**Comment by Titogelo** [comment]
http://stackoverflow.com/questions/8147221/best-method-of-channel-pooling-in-google-app-engine
